### PR TITLE
Initial move to gradle

### PR DESCRIPTION
**Pull request by imurchie**
Currently this is built with the old Android tools (version 22 is the last that works) so any change necessitates some moving of things to get the build to work. 

This is the product of Android Studio's import, with the JS stuff pulled over manually. The package works with tests on real and emulated devices in both `appium-android-driver` and `appium-uiautomator2-driver`.

### CODE REVIEW

**Comment by imurchie** [comment]
The problem with that is the modifications we've made to handle some of our test scenarios. We would need to catalog all that and then re-implement.

**Comment by jlipps** [comment]
Fair point. The only modification I remember making was adding content descriptions to the main view, but I can't say whether anyone else did anything else to it. Probably did.

**Comment by imurchie** [comment]
I know we've added extra webviews, as well as a number of different kinds of text fields to a single view. Probably others.

But as far as I can tell, this PR represents everything that is needed to upgrade to Gradle.

**Comment by jlipps** [comment]
👉 make this 9k-line change so, then 👉

**Comment by imurchie** [comment]
Thanks, Captain!

**Pull request merged**
