### PR TITLE
chore: Update Gradle

### PR DESCRIPTION
**Pull request by Dor-bl**
Upgrade APG from 7.4.2 to 8.0.2 Also updated gradle to version 8.2.1

Moved package from Android manifest to build files since Declaration of a project's namespace using the package attribute of the Android manifest is deprecated in favour of a namespace declaration in build files.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I am not convinced we should do it as v8 requires min Java 17 to build the project: https://github.com/appium/android-apidemos/actions/runs/5525154090/jobs/10078402322?pr=107

**Comment by Dor-bl** [comment]
> I am not convinced we should do it as v8 requires min Java 17 to build the project: https://github.com/appium/android-apidemos/actions/runs/5525154090/jobs/10078402322?pr=107

That's why I created this PR: https://github.com/appium/android-apidemos/pull/108

**Comment by mykola-mokhnach** [comment]
Lets merge that PR first and then rebase this one afterwards

**Comment by Dor-bl** [comment]
@mykola-mokhnach https://github.com/appium/android-apidemos/pull/108 was merged

**Review by KazuCocoa — APPROVED** [review]

**Comment by Dor-bl** [comment]
@mykola-mokhnach/ @KazuCocoa  can you merge, please?

**Pull request merged**
