### PR TITLE
Target SDK 33

### PR DESCRIPTION
**Pull request by Dor-bl**
Removed deprecated `buildToolsVersion`
replaced `compileSdkVersion`  with `compileSdk`
Target SDK 33
Bump `appcompat` from 1.4.2 to 1.6.1
Bump `versionName` to 4.2.0

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Comment by Dor-bl** [comment]
@KazuCocoa @mykola-mokhnach I think I missed updating the corresponding app version here: https://github.com/appium/android-apidemos/blob/master/package.json#L3

**Comment by mykola-mokhnach** [comment]
This version must not be updated manually. It is a part of the package publishing flow

**Comment by mykola-mokhnach** [comment]
I would also advice to sync android package version bump with npm version bump similarly to how it's done in https://github.com/appium/io.appium.settings/blob/5d3bc99ff35f3b816b4342395aba1bdea82ad48f/package.json#L15

**Comment by Dor-bl** [comment]
So you usually change the `${npm_package_version}` value and run the command?

**Pull request merged**
